### ISSUE TITLE
Some questions about acceptance test projects

### ISSUE THREAD

**Issue by AndrewZhao** [NetFPGA/NetFPGA-SUME-public#1]
Now I have got a new netfpga-sume board , In which way can I get the acceptance test projects you have mentioned in home page?

**Comment by litaotju** [comment]
I have met the same question with you. I would like to know the solutions already ? Thanks So much for any replyment..

**Comment by noaz** [comment]
Hello,
See Section II of [Getting Started Guide](https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Getting-Started-Guide)
