### ISSUE TITLE
Issue when openning a serial terminal

### ISSUE THREAD

**Issue by ederollora** [NetFPGA/NetFPGA-SUME-public#14]
We have tried to connect to the serial interface using the USB cable to make sure the board was responding though we have not been able to get any output from the board. (LED 10 and 4 are working properly).
Here the different OSs, apps and combinations we have tested:

- Ubuntu Server 16.04 and 14.04 (different kernels in 16.04 including 4.10 in case that could affect)
- USB 2.0 and 3.0 ports. Also different USB cables
- Different PCI slots (although we are almost sure this does not affect for serial com)
- Minicom, Putty, picocom, gtkterm ... None showing any output
  - Conf: 115200, 8N1, no flow control

At this point we are not sure what we are doing wrong as we tested 2 boards. We though that to communicate with the board we did not need any particular drivers or apps installed but we did try installing Vivado too with no success (either in minicom, again, or actually configuring the target in Vivado but we might come to that in another step).

So, do we need any special drivers or apps (that are not the dependencies listed) to be able to open com terminal?

The picture below is what we always get. 

<img width="495" alt="capture1" src="https://user-images.githubusercontent.com/3457431/53754660-e5af0a00-3eb4-11e9-986d-8b7482ce805f.PNG">

**Comment by hendrikzuellig** [comment]
I had to use another Micro USB cable since the one that arrived with the NetFPGA SUME Board didn't work.
I'm assuming you are at this [step](
https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Getting-Started-Guide#section-iv-netfpga-sume-first-power-up) 
Have you tried to press the `PROG`Button on the board while connected? That got me the expected output

**Comment by salvatorg** [comment]
> We have tried to connect to the serial interface using the USB cable to make sure the board was responding though we have not been able to get any output from the board. (LED 10 and 4 are working properly).
> Here the different OSs, apps and combinations we have tested:
> 
> * Ubuntu Server 16.04 and 14.04 (different kernels in 16.04 including 4.10 in case that could affect)
> * USB 2.0 and 3.0 ports. Also different USB cables
> * Different PCI slots (although we are almost sure this does not affect for serial com)
> * Minicom, Putty, picocom, gtkterm ... None showing any output
>   
>   * Conf: 115200, 8N1, no flow control
> 
> At this point we are not sure what we are doing wrong as we tested 2 boards. We though that to communicate with the board we did not need any particular drivers or apps installed but we did try installing Vivado too with no success (either in minicom, again, or actually configuring the target in Vivado but we might come to that in another step).
> 
> So, do we need any special drivers or apps (that are not the dependencies listed) to be able to open com terminal?
> 
> The picture below is what we always get.
> 
> <img alt="capture1" width="495" src="https://user-images.githubusercontent.com/3457431/53754660-e5af0a00-3eb4-11e9-986d-8b7482ce805f.PNG">

@ederollora , couple of things to consider.

- the NetFPGA-SUME hasn't been tested with Ubuntu Server OS. (I guess that you might need to install additional lib, tools etc)
- have you tried [digilent tools](https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Reference-Operating-System-Setup-Guide#installation-of-digilent-adept-tools)

**Comment by ederollora** [comment]
Thanks @salvatorg . It was my fault to not close the issue, I did solve it with @hendrikzuellig 's advices. Just for curiosity, which OS do you normally use if not Ubuntu?

Thanks!
