### ISSUE TITLE
Dose NetFPGA SUME supports Multicasting or Mirroring?

### ISSUE THREAD

**Issue by quejinkook** [NetFPGA/NetFPGA-SUME-public#16]
Dear all.
I am new to the NetFPGA SUME.

I wonder if the NetFPGA SUME supports **packet copy** features for 
**Multicasting or Mirroring.**

Is there **any document or source code** for the packet copy functions?? 

Thanks.

**Comment by salvatorg** [comment]
Can you be more specific? For example, reference_switch supports flooding.
Could you explain more the packet copy functions?

**Comment by quejinkook** [comment]
Dear @salvatorg .
Thank you for your reply.

I want to implement mirroring scenario which copies all traffic at dedicated port(e.g. port0) and send them to the other(e.g. cpu) port. 

For example, I want to copy all outgoing traffic at nf0 and send them to the dma port.
