### ISSUE TITLE
Accpetance test - Internal Python error

### ISSUE THREAD

**Issue by mangorius** [NetFPGA/NetFPGA-SUME-public#24]
I followed the acceptance test guide.
Build was successful, starting the GUI was successful, but starting any test prints the following error to the console, while the Test GUI is counting elapsed time infinitely:

```
Create Progress
---------------------------------------------
[sata]: Running Auto Test
---------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "sw/host/script/NfSumeTest.py", line 947, in run
    self.target(*self.data)
  File "sw/host/script/NfSumeTest.py", line 465, in TestInterface
    self.ProgramFpga('../../../bitfiles/' + self.nfSumeTestConfiguration[testName]['bitstream'])
  File "sw/host/script/NfSumeTest.py", line 586, in ProgramFpga
    self.getFpgaIndex()
  File "sw/host/script/NfSumeTest.py", line 574, in getFpgaIndex
    p = Popen(['djtgcfg', 'init', '-d', 'NetSUME'], stdout=PIPE, bufsize = 1)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The build of the bitfiles ran before (about 20 minutes each) and I wasn't able to see any error there.

My system:
Ubuntu 18.04 latest updates
NetFPGA SUME

Does anyone know how to fix this?
I already created a design with Vivado for testing LEDs, switches and UART via USB, that's working, but I'd like to test all peripherals.

**Comment by salvatorg** [comment]
Hi,
python3 is included by default in Ubuntu 18.04.
The python test infrastructure of the NetFPGA-SUME is based on python2.7 
Check which version the python commands gives u and set it to version 2.7

**Comment by mangorius** [comment]
Hi,

thank you for your fast response.
Unfortunately this is not the problem:

```
pc1:~$ python --version
Python 2.7.15+
```

**Comment by salvatorg** [comment]
Just to confirm, have you generated the bitfiles?

**Comment by mangorius** [comment]
I think the bitfiles are generated automatically when launching a test the first time.

```
pc1:~/NetFPGA-SUME-live-master/projects/acceptance_test/bitfiles$ ll
total 34M
drwxrwxr-x 2 kevin kevin   4,0K Nov 11 09:45 ./
drwxrwxr-x 6 kevin kevin   4,0K Jul 29  2018 ../
-rw-r--r-- 1 kevin dialout 6,4M Nov  6 13:00 nf_sume_ddr3A.bit
-rw-r--r-- 1 kevin kevin   6,5M Nov 11 09:45 nf_sume_ddr3B.bit
-rw-r--r-- 1 kevin kevin   5,7M Nov 11 09:16 nf_sume_qdrA.bit
-rw-r--r-- 1 kevin kevin   5,5M Nov 11 08:51 nf_sume_qdrC.bit
-rw-r--r-- 1 kevin dialout 5,9M Nov  6 11:57 nf_sume_qth_gtwizard.bit
-rw-r--r-- 1 kevin dialout 4,3M Nov  6 12:16 nf_sume_sata.bit
-rwxr-xr-x 1 kevin kevin   2,8K Jul 29  2018 README*
```

**Comment by salvatorg** [comment]
hmm ok the bitfiles are there so you have already modified and source the NetFPGA-SUME/tools/settings.sh accordingly.
Did u try to launch the python test GUI explicitly with python2 ?
i.e. $ python2 $NF_DESIGN_DIR/sw/host/script/NfSumeTest.py?

**Comment by mangorius** [comment]
I modified and sourced it, yes.
I just checked again, if there is an error (I assumed there is no, because compiling bitfiles worked), and there is definitely something wrong:

the `tools/settings.sh` sets $PYTHONPATH to three different pathes. The second one does not exist: `${NF_DESIGN_DIR}/lib/Python`

There is no `lib` folder:
```
pc1:~/NetFPGA-SUME-live-master/projects/acceptance_test$ ll /home/kevin/projects/NetFPGA-SUME-live-master/projects/acceptance_test/
total 28K
drwxrwxr-x  6 kevin kevin 4,0K Jul 29  2018 ./
drwxrwxr-x  8 kevin kevin 4,0K Jul 29  2018 ../
drwxrwxr-x  2 kevin kevin 4,0K Nov 11 09:45 bitfiles/
drwxrwxr-x 10 kevin kevin 4,0K Nov 11 09:42 hw/
drwxrwxr-x  4 kevin kevin 4,0K Jul 29  2018 ip_repo/
-rwxr-xr-x  1 kevin kevin 2,2K Jul 29  2018 Makefile*
drwxrwxr-x  4 kevin kevin 4,0K Jul 29  2018 sw/
```

Maybe this is the problem.
Anyway, I started the python script directly with python2, as you proposed, no difference.

**Comment by salvatorg** [comment]
You are right, this might be a typo.. but in any case PYTHONPATH only affects import statements..
Somethings to try..
i. you have installed [digilent tools](https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Reference-Operating-System-Setup-Guide#installation-of-digilent-adept-tools)?
ii. do u run the test as a root?

**Comment by mangorius** [comment]
I did not run the test as root, but that wasn't necessary.
I just thought digilent tools were only necessary when not using vivado, sorry...
I think it would be nice for the future to show an error message like "Digilent tools not found".

**After installing vivado tools, tests are running.**
Thank you so much for your help!
