### ISSUE TITLE
Related to vivado version issues

### ISSUE THREAD

**Issue by ngominh911** [NetFPGA/NetFPGA-SUME-public#27]
Hello Sir,

I have a problem that need your advises:

As NetFPGA-SUME software recommendation page suggests to use Vivado 2014 or 2016. We installed it and it works well. However, when we try Vivado 2018.2, there are a lot of bugs related to IP versions. 
Should we try to fix all the bugs or just use 2016 version? Thank you!

**Comment by salvatorg** [comment]
Hi @ngominh911 ,

The short answer is, it depends on you.
The recommended version for Vivado is v2016.4. If you really want to play around with newest version of Vivado, it is up to you. But have in mind that you might run into lot of compatibility issues which you ll have to fix by yourself.

**Comment by ngominh911** [comment]
Because I also want to make connection with P4 project and they run on
Vivado 2018. Thank you for your help. I will work separately in both
versions first.

**Comment by salvatorg** [comment]
If you want to work only with the P4-NetFPGA code base then Vivado v2018.2 is sufficient.
A hint: if you ll work with both versions then make sure to source the correct settings (Vivado + code base) every time.
