### ISSUE TITLE
error of git clone 

### ISSUE THREAD

**Issue by jia1546** [NetFPGA/NetFPGA-SUME-public#7]
When I executed "git clone https://github.com/NetFPGA/NetFPGA-SUME-live.git", it returned
remote: Repository not found.
fatal: repository 'https://github.com/NetFPGA/NetFPGA-SUME-live.git/' not found

**Comment by muralisr** [comment]
Hello, please ensure you have access to the repository. Have you filled up the registration form at [this](https://netfpga.org/site/#/SUME_reg_form/) link?

**Comment by jia1546** [comment]
I have submitted a registration. Thanks!
