### ISSUE TITLE
error in constraint file for project reference_nic

### ISSUE THREAD

**Issue by jia1546** [NetFPGA/NetFPGA-SUME-public#8]
in file nf_sume_general_bd.xdc, the pcie_sys_resetn is binded to PACKAGE_PIN AY35 (line 43). However, according to the VC709 schematic, it should be pin "AV35".   
![image](https://user-images.githubusercontent.com/859937/45207784-8d0f0380-b2bb-11e8-8679-56bf70ac2d97.png)

**Comment by salvatorg** [comment]
Hi @jia1546 , thank you for bringing this up. I will contact and verify with Digilent thats the correct connection. Once I have an answer I will post it here.

**Comment by noaz** [comment]
Hi @jia1546 @salvatorg,

The pinout of sume is different to VC709, see [SUME schematics](https://github.com/NetFPGA/NetFPGA-SUME-live/blob/master/docs/NetFPGA-SUME_schematics.pdf).
The xdc file matches the SUME board.
