### ISSUE TITLE
how to create a small and basic netfpga project ?

### ISSUE THREAD

**Issue by Maskerk** [NetFPGA/NetFPGA-SUME-public#9]
i can't find a tutorial that can teach me how to create a netfpga project on google . how to create a small and basic netfpga project ? thanks.

**Comment by salvatorg** [comment]
I would suggest you to start with an already implemented reference project and modify that.
The simplest reference project you can start working on is the reference_switch_lite.
Changing the behaviour of the switch to your requirements is very simple in that project. Take a look at the output_port_lookup module.
